In [30]:
#%pip install pandas numpy seaborn matplotlib

In [3]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
price_df = pd.read_csv(r"DATA/Bakeryprice.csv")

In [5]:
sales_df = pd.read_csv("DATA/Bakerysales.csv")

In [6]:
# ==========================================
# DIMENSIONES INICIALES DE LOS DATASETS
# ==========================================

print("Shape prices_df:", price_df.shape)
print("Shape sales_df:", sales_df.shape)

Shape prices_df: (22, 2)
Shape sales_df: (2654, 27)

In [7]:
sales_df.head()

,datetime,day of week,total,place,angbutter,plain bread,jam,americano,croissant,caffe latte,...,gateau chocolat,pandoro,cheese cake,lemon ade,orange pound,wiener,vanila latte,berry ade,tiramisu,merinque cookies
0,2019-07-11 15:35,Thur,23800.0,NaN,1.0,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
1,2019-07-11 16:10,Thur,15800.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
2,2019-07-12 11:49,Fri,58000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019-07-13 13:19,Sat,14800.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
4,2019-07-13 13:22,Sat,15600.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
sales_df.isnull().sum().sort_values(ascending=False)

croque monsieur       2654
mad garlic            2654
tiramisu              2647
lemon ade             2619
merinque cookies      2607
berry ade             2600
cheese cake           2564
milk tea              2517
caffe latte           2461
gateau chocolat       2458
almond croissant      2452
vanila latte          2445
jam                   2434
cacao deep            2331
pandoro               2311
wiener                2299
americano             2242
orange pound          2135
pain au chocolat      2067
croissant             1907
tiramisu croissant    1875
plain bread           1797
angbutter              681
place                  488
day of week            234
total                  234
datetime               233
dtype: int64

In [9]:
sales_df.duplicated().sum()

np.int64(232)

In [10]:
price_df.isnull().sum()

Name     0
price    0
dtype: int64

In [36]:
price_df

                  Name      price
0            angbutter       4800
1          plain bread       3500
2                  jam       1500
3            ice coffe       4000
4            croissant       3500
5     ice coffe latter       4500
6   tiramisu croissant       4800
7           cacao deep       4000
8     pain au chocolat       3500
9     almond croissant       4000
10        ice milk tea       4500
11     gateau chocolat       4000
12             pandoro       4500
13         cheese cake       5000
14           lemon ade       4500
15        orange pound       4500
16              wiener       2500
17        valina latte       4500
18           berry ade       4500
19            tiramisu       4500
20    merinque cookies       4000
21        delivery fee  2000~4000

In [11]:
#analizar null y duplicados en dfprice
price_df.isnull().sum()
price_df.duplicated().sum()

np.int64(0)

In [12]:
sales_df.duplicated().sum()

np.int64(232)

In [13]:
# ==========================================
# CONVERSIÓN ROBUSTA DE DATETIME
# ==========================================

sales_df['datetime'] = pd.to_datetime(
    sales_df['datetime'],
    errors='coerce'
)
# eliminar fechas corruptas convertidas en NaT
sales_df = sales_df.dropna(subset=['datetime'])

sales_df.isnull().sum().sort_values(ascending=False)

croque monsieur       2421
mad garlic            2421
tiramisu              2414
lemon ade             2386
merinque cookies      2374
berry ade             2367
cheese cake           2331
milk tea              2284
caffe latte           2228
gateau chocolat       2225
almond croissant      2219
vanila latte          2212
jam                   2201
cacao deep            2098
pandoro               2078
wiener                2066
americano             2009
orange pound          1902
pain au chocolat      1834
croissant             1674
tiramisu croissant    1642
plain bread           1564
angbutter              448
place                  255
day of week              1
total                    1
datetime                 0
dtype: int64

In [14]:
sales_df['datetime'] = pd.to_datetime(sales_df['datetime'])
sales_df.info()

<class 'pandas.DataFrame'>
Index: 2421 entries, 0 to 2653
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   datetime            2421 non-null   datetime64[us]
 1   day of week         2420 non-null   str
 2   total               2420 non-null   float64
 3   place               2166 non-null   str
 4   angbutter           1973 non-null   float64
 5   plain bread         857 non-null    float64
 6   jam                 220 non-null    float64
 7   americano           412 non-null    float64
 8   croissant           747 non-null    float64
 9   caffe latte         193 non-null    float64
 10  tiramisu croissant  779 non-null    float64
 11  cacao deep          323 non-null    float64
 12  pain au chocolat    587 non-null    float64
 13  almond croissant    202 non-null    float64
 14  croque monsieur     0 non-null      float64
 15  mad garlic          0 non-null      float64
 16  milk tea            137 non-null    float64
 17  gateau chocolat     196 non-null    float64
 18  pandoro             343 non-null    float64
 19  cheese cake         90 non-null     float64
 20  lemon ade           35 non-null     float64
 21  orange pound        519 non-null    float64
 22  wiener              355 non-null    float64
 23  vanila latte        209 non-null    float64
 24  berry ade           54 non-null     float64
 25  tiramisu            7 non-null      float64
 26  merinque cookies    47 non-null     float64
dtypes: datetime64[us](1), float64(24), str(2)
memory usage: 529.6 KB

In [16]:
id_columns = ['datetime', 'day of week', 'total', 'place']
product_columns = [col for col in sales_df.columns if col not in id_columns]

In [17]:
sales_df[product_columns] = sales_df[product_columns].fillna(0)

In [18]:
sales_df.duplicated().sum()

np.int64(0)

In [19]:
sales_long = sales_df.melt(
    id_vars=id_columns,
    value_vars=product_columns,
    var_name='product',
    value_name='quantity'
)

In [20]:
sales_long = sales_long[sales_long['quantity'] > 0]

In [21]:
sales_long.head(20)

              datetime day of week    total place    product  quantity
0  2019-07-11 15:35:00        Thur  23800.0   NaN  angbutter       1.0
1  2019-07-11 16:10:00        Thur  15800.0   NaN  angbutter       1.0
3  2019-07-13 13:19:00         Sat  14800.0   NaN  angbutter       1.0
4  2019-07-13 13:22:00         Sat  15600.0   NaN  angbutter       2.0
5  2019-07-13 14:54:00         Sat  15800.0   NaN  angbutter       1.0
6  2019-07-13 15:08:00         Sat  15800.0   NaN  angbutter       1.0
8  2019-07-13 15:23:00         Sat  19100.0   NaN  angbutter       2.0
9  2019-07-13 16:32:00         Sat  22300.0   NaN  angbutter       1.0
10 2019-07-14 11:08:00         Sun  15300.0   NaN  angbutter       1.0
11 2019-07-14 11:15:00         Sun  27600.0   NaN  angbutter       2.0
12 2019-07-14 11:44:00         Sun  26300.0   NaN  angbutter       1.0
13 2019-07-14 11:59:00         Sun  19800.0   NaN  angbutter       1.0
14 2019-07-14 12:59:00         Sun  18300.0   NaN  angbutter       1.0
15 2019-07-14 13:05:00         Sun  15600.0   NaN  angbutter       2.0
16 2019-07-14 14:06:00         Sun  23600.0   NaN  angbutter       2.0
17 2019-07-14 14:41:00         Sun  20100.0   NaN  angbutter       2.0
18 2019-07-14 14:51:00         Sun  25600.0   NaN  angbutter       2.0
19 2019-07-14 15:02:00         Sun  19800.0   NaN  angbutter       1.0
20 2019-07-15 11:45:00         Mon  15100.0   NaN  angbutter       2.0
21 2019-07-15 16:21:00         Mon  15800.0   NaN  angbutter       1.0

In [28]:
# ==========================================
# NORMALIZACIÓN DE TEXTO EN PRODUCTOS
# ==========================================

# en ventas
sales_long['product'] = (
    sales_long['product']
    .str.strip()        # elimina espacios
    .str.lower()        # minúsculas
)

# en precios
price_df['Name'] = (
    price_df['Name']
    .str.strip()
    .str.lower()
)

In [29]:
df = sales_long.merge(
    price_df,
    left_on='product',
    right_on='Name',
    how='left'
)

In [30]:
df[df['price'].isnull()]

,datetime,day of week,total,place,product,quantity,Name,price
3050,2019-07-11 15:35:00,Thur,23800.0,NaN,americano,1.0,NaN,NaN
3051,2019-07-14 11:15:00,Sun,27600.0,NaN,americano,3.0,NaN,NaN
3052,2019-07-20 11:35:00,Sat,18800.0,NaN,americano,1.0,NaN,NaN
3053,2019-07-20 13:56:00,Sat,17800.0,NaN,americano,1.0,NaN,NaN
3054,2019-07-21 12:12:00,Sun,17800.0,NaN,americano,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...
8172,2020-04-18 14:10:00,Sat,36000.0,석사동,vanila latte,1.0,NaN,NaN
8173,2020-04-20 12:32:00,Mon,16500.0,퇴계동,vanila latte,1.0,NaN,NaN
8174,2020-04-25 16:13:00,Sat,15800.0,후평 1동,vanila latte,1.0,NaN,NaN
8175,2020-04-26 12:00:00,Sun,23300.0,강남동,vanila latte,1.0,NaN,NaN
8176,2020-05-02 11:37:00,Sat,19500.0,동면,vanila latte,1.0,NaN,NaN

In [31]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 8285 entries, 0 to 8284
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   datetime     8285 non-null   datetime64[us]
 1   day of week  8285 non-null   str
 2   total        8285 non-null   float64
 3   place        7408 non-null   str
 4   product      8285 non-null   str
 5   quantity     8285 non-null   float64
 6   Name         7334 non-null   str
 7   price        7334 non-null   str
dtypes: datetime64[us](1), float64(2), str(5)
memory usage: 517.9 KB

                         datetime         total     quantity
count                        8285  8.285000e+03  8285.000000
mean   2019-12-11 14:57:54.995775  2.260753e+04     1.308389
min           2019-07-11 15:35:00  1.280000e+04     1.000000
25%           2019-09-22 12:08:00  1.600000e+04     1.000000
50%           2019-12-14 13:14:00  1.930000e+04     1.000000
75%           2020-02-27 11:25:00  2.430000e+04     1.000000
max           2020-05-02 14:45:00  1.293000e+06    16.000000
std                           NaN  3.520208e+04     0.790994

In [32]:
df.head()

,datetime,day of week,total,place,product,quantity,Name,price
0,2019-07-11 15:35:00,Thur,23800.0,NaN,angbutter,1.0,angbutter,4800
1,2019-07-11 16:10:00,Thur,15800.0,NaN,angbutter,1.0,angbutter,4800
2,2019-07-13 13:19:00,Sat,14800.0,NaN,angbutter,1.0,angbutter,4800
3,2019-07-13 13:22:00,Sat,15600.0,NaN,angbutter,2.0,angbutter,4800
4,2019-07-13 14:54:00,Sat,15800.0,NaN,angbutter,1.0,angbutter,4800

In [33]:
# ==========================================
# VALIDACIÓN DE PRODUCTOS SIN PRECIO
# ==========================================

missing_prices = df['price'].isnull().sum()

print("Productos sin precio:", missing_prices)

# visualizar productos problemáticos
df[df['price'].isnull()]

Productos sin precio: 951

,datetime,day of week,total,place,product,quantity,Name,price
3050,2019-07-11 15:35:00,Thur,23800.0,NaN,americano,1.0,NaN,NaN
3051,2019-07-14 11:15:00,Sun,27600.0,NaN,americano,3.0,NaN,NaN
3052,2019-07-20 11:35:00,Sat,18800.0,NaN,americano,1.0,NaN,NaN
3053,2019-07-20 13:56:00,Sat,17800.0,NaN,americano,1.0,NaN,NaN
3054,2019-07-21 12:12:00,Sun,17800.0,NaN,americano,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...
8172,2020-04-18 14:10:00,Sat,36000.0,석사동,vanila latte,1.0,NaN,NaN
8173,2020-04-20 12:32:00,Mon,16500.0,퇴계동,vanila latte,1.0,NaN,NaN
8174,2020-04-25 16:13:00,Sat,15800.0,후평 1동,vanila latte,1.0,NaN,NaN
8175,2020-04-26 12:00:00,Sun,23300.0,강남동,vanila latte,1.0,NaN,NaN
8176,2020-05-02 11:37:00,Sat,19500.0,동면,vanila latte,1.0,NaN,NaN

In [ ]:
# ==========================================
# IDENTIFICAR PRODUCTOS SIN PRECIO
# ==========================================
# ==========================================
# CORRECCIÓN MANUAL DE NOMBRES DE PRODUCTOS
# ==========================================

product_mapping = {
    'ice coffe': 'americano',
    'latte coffee': 'caffe latte',
    'ice milk tea': 'milk tea',
    'valina latte': 'vanilla latte'
}

df['product'] = df['product'].replace(product_mapping)
missing_products = df[df['price'].isnull()]['product'].unique()

print("Productos sin match en precios:")
print(missing_products)

Productos sin match en precios:
<StringArray>
['americano', 'caffe latte', 'milk tea', 'vanila latte']
Length: 4, dtype: str

In [35]:
missing_products = df[df['price'].isnull()]['product'].unique()

print("Productos sin match tras normalización:")
print(missing_products)

Productos sin match tras normalización:
<StringArray>
['americano', 'caffe latte', 'milk tea', 'vanila latte']
Length: 4, dtype: str