In [30]:
#%pip install pandas numpy seaborn matplotlib

In [31]:
import pandas as pd 
import numpy as np
import seaborn as sbn
import matplotlib  as plt

In [32]:
dfprice = pd.read_csv(r"data/Bakeryprice.csv")
dfprice.info()

<class 'pandas.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    22 non-null     str
 1   price   22 non-null     str
dtypes: str(2)
memory usage: 484.0 bytes

In [33]:
dfsales = pd.read_csv("data/Bakerysales.csv")

In [34]:
dfsales.info()

<class 'pandas.DataFrame'>
RangeIndex: 2654 entries, 0 to 2653
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   datetime            2421 non-null   str
 1   day of week         2420 non-null   str
 2   total               2420 non-null   float64
 3   place               2166 non-null   str
 4   angbutter           1973 non-null   float64
 5   plain bread         857 non-null    float64
 6   jam                 220 non-null    float64
 7   americano           412 non-null    float64
 8   croissant           747 non-null    float64
 9   caffe latte         193 non-null    float64
 10  tiramisu croissant  779 non-null    float64
 11  cacao deep          323 non-null    float64
 12  pain au chocolat    587 non-null    float64
 13  almond croissant    202 non-null    float64
 14  croque monsieur     0 non-null      float64
 15  mad garlic          0 non-null      float64
 16  milk tea            137 non-null    float64
 17  gateau chocolat     196 non-null    float64
 18  pandoro             343 non-null    float64
 19  cheese cake         90 non-null     float64
 20  lemon ade           35 non-null     float64
 21  orange pound        519 non-null    float64
 22  wiener              355 non-null    float64
 23  vanila latte        209 non-null    float64
 24  berry ade           54 non-null     float64
 25  tiramisu            7 non-null      float64
 26  merinque cookies    47 non-null     float64
dtypes: float64(24), str(3)
memory usage: 560.0 KB

In [35]:
dfsales.head()

,datetime,day of week,total,place,angbutter,plain bread,jam,americano,croissant,caffe latte,...,gateau chocolat,pandoro,cheese cake,lemon ade,orange pound,wiener,vanila latte,berry ade,tiramisu,merinque cookies
0,2019-07-11 15:35,Thur,23800.0,NaN,1.0,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
1,2019-07-11 16:10,Thur,15800.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
2,2019-07-12 11:49,Fri,58000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019-07-13 13:19,Sat,14800.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
4,2019-07-13 13:22,Sat,15600.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
dfsales.isnull().sum().sort_values(ascending=False)

croque monsieur       2654
mad garlic            2654
tiramisu              2647
lemon ade             2619
merinque cookies      2607
berry ade             2600
cheese cake           2564
milk tea              2517
caffe latte           2461
gateau chocolat       2458
almond croissant      2452
vanila latte          2445
jam                   2434
cacao deep            2331
pandoro               2311
wiener                2299
americano             2242
orange pound          2135
pain au chocolat      2067
croissant             1907
tiramisu croissant    1875
plain bread           1797
angbutter              681
place                  488
day of week            234
total                  234
datetime               233
dtype: int64

In [39]:
dfsales.duplicated().sum()

np.int64(232)

In [ ]:
#analizar null y duplicados en dfprice
dfprice.isnull().sum()
dfprice.duplicated().sum()

np.int64(0)

In [40]:
# remplazar productos por cero 
dfsales[dfsales['datetime'].isnull()]

,datetime,day of week,total,place,angbutter,plain bread,jam,americano,croissant,caffe latte,...,gateau chocolat,pandoro,cheese cake,lemon ade,orange pound,wiener,vanila latte,berry ade,tiramisu,merinque cookies
2420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2421,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2422,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2423,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2424,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2648,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2649,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2650,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2651,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2652,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
dfsales = dfsales.dropna(subset=['datetime'])
dfsales.isnull().sum().sort_values(ascending=False)

croque monsieur       2421
mad garlic            2421
tiramisu              2414
lemon ade             2386
merinque cookies      2374
berry ade             2367
cheese cake           2331
milk tea              2284
caffe latte           2228
gateau chocolat       2225
almond croissant      2219
vanila latte          2212
jam                   2201
cacao deep            2098
pandoro               2078
wiener                2066
americano             2009
orange pound          1902
pain au chocolat      1834
croissant             1674
tiramisu croissant    1642
plain bread           1564
angbutter              448
place                  255
day of week              1
total                    1
datetime                 0
dtype: int64

In [46]:
dfsales['datetime'] = pd.to_datetime(dfsales['datetime'])
dfsales.info()

<class 'pandas.DataFrame'>
Index: 2421 entries, 0 to 2653
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   datetime            2421 non-null   datetime64[us]
 1   day of week         2420 non-null   str
 2   total               2420 non-null   float64
 3   place               2166 non-null   str
 4   angbutter           1973 non-null   float64
 5   plain bread         857 non-null    float64
 6   jam                 220 non-null    float64
 7   americano           412 non-null    float64
 8   croissant           747 non-null    float64
 9   caffe latte         193 non-null    float64
 10  tiramisu croissant  779 non-null    float64
 11  cacao deep          323 non-null    float64
 12  pain au chocolat    587 non-null    float64
 13  almond croissant    202 non-null    float64
 14  croque monsieur     0 non-null      float64
 15  mad garlic          0 non-null      float64
 16  milk tea            137 non-null    float64
 17  gateau chocolat     196 non-null    float64
 18  pandoro             343 non-null    float64
 19  cheese cake         90 non-null     float64
 20  lemon ade           35 non-null     float64
 21  orange pound        519 non-null    float64
 22  wiener              355 non-null    float64
 23  vanila latte        209 non-null    float64
 24  berry ade           54 non-null     float64
 25  tiramisu            7 non-null      float64
 26  merinque cookies    47 non-null     float64
dtypes: datetime64[us](1), float64(24), str(2)
memory usage: 529.6 KB