In [30]:
#%pip install pandas numpy seaborn matplotlib

In [63]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [92]:
price_df = pd.read_csv(r"DATA/Bakeryprice.csv")

In [93]:
sales_df = pd.read_csv("DATA/Bakerysales.csv")

In [95]:
# ==========================================
# DIMENSIONES INICIALES DE LOS DATASETS
# ==========================================

print("Shape prices_df:", price_df.shape)
print("Shape sales_df:", sales_df.shape)

Shape prices_df: (22, 2)
Shape sales_df: (2654, 27)

In [96]:
sales_df.head()

,datetime,day of week,total,place,angbutter,plain bread,jam,americano,croissant,caffe latte,...,gateau chocolat,pandoro,cheese cake,lemon ade,orange pound,wiener,vanila latte,berry ade,tiramisu,merinque cookies
0,2019-07-11 15:35,Thur,23800.0,NaN,1.0,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
1,2019-07-11 16:10,Thur,15800.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
2,2019-07-12 11:49,Fri,58000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019-07-13 13:19,Sat,14800.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
4,2019-07-13 13:22,Sat,15600.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [127]:
sales_df.isnull().sum().sort_values(ascending=False)

place                 255
total                   1
day of week             1
datetime                0
angbutter               0
plain bread             0
jam                     0
americano               0
croissant               0
caffe latte             0
tiramisu croissant      0
cacao deep              0
pain au chocolat        0
almond croissant        0
croque monsieur         0
mad garlic              0
milk tea                0
gateau chocolat         0
pandoro                 0
cheese cake             0
lemon ade               0
orange pound            0
wiener                  0
vanila latte            0
berry ade               0
tiramisu                0
merinque cookies        0
dtype: int64

In [128]:
sales_df.duplicated().sum()

np.int64(0)

In [144]:
price_df.isnull().sum()

Name     0
price    0
dtype: int64

In [145]:
#analizar null y duplicados en dfprice
price_df.isnull().sum()
price_df.duplicated().sum()

np.int64(0)

In [146]:
sales_df.duplicated().sum()

np.int64(0)

In [131]:
# ==========================================
# CONVERSIÓN ROBUSTA DE DATETIME
# ==========================================

sales_df['datetime'] = pd.to_datetime(
    sales_df['datetime'],
    errors='coerce'
)
# eliminar fechas corruptas convertidas en NaT
sales_df = sales_df.dropna(subset=['datetime'])

sales_df.isnull().sum().sort_values(ascending=False)

place                 255
total                   1
day of week             1
datetime                0
angbutter               0
plain bread             0
jam                     0
americano               0
croissant               0
caffe latte             0
tiramisu croissant      0
cacao deep              0
pain au chocolat        0
almond croissant        0
croque monsieur         0
mad garlic              0
milk tea                0
gateau chocolat         0
pandoro                 0
cheese cake             0
lemon ade               0
orange pound            0
wiener                  0
vanila latte            0
berry ade               0
tiramisu                0
merinque cookies        0
dtype: int64

In [147]:
sales_df['datetime'] = pd.to_datetime(sales_df['datetime'])
sales_df.info()

<class 'pandas.DataFrame'>
Index: 2421 entries, 0 to 2653
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   datetime            2421 non-null   datetime64[us]
 1   day of week         2420 non-null   str
 2   total               2420 non-null   float64
 3   place               2166 non-null   str
 4   angbutter           2421 non-null   float64
 5   plain bread         2421 non-null   float64
 6   jam                 2421 non-null   float64
 7   americano           2421 non-null   float64
 8   croissant           2421 non-null   float64
 9   caffe latte         2421 non-null   float64
 10  tiramisu croissant  2421 non-null   float64
 11  cacao deep          2421 non-null   float64
 12  pain au chocolat    2421 non-null   float64
 13  almond croissant    2421 non-null   float64
 14  croque monsieur     2421 non-null   float64
 15  mad garlic          2421 non-null   float64
 16  milk tea            2421 non-null   float64
 17  gateau chocolat     2421 non-null   float64
 18  pandoro             2421 non-null   float64
 19  cheese cake         2421 non-null   float64
 20  lemon ade           2421 non-null   float64
 21  orange pound        2421 non-null   float64
 22  wiener              2421 non-null   float64
 23  vanila latte        2421 non-null   float64
 24  berry ade           2421 non-null   float64
 25  tiramisu            2421 non-null   float64
 26  merinque cookies    2421 non-null   float64
dtypes: datetime64[us](1), float64(24), str(2)
memory usage: 529.6 KB

In [133]:
id_columns = ['datetime', 'day of week', 'total', 'place']
product_columns = [col for col in dfsales.columns if col not in id_columns]

In [134]:
sales_df[product_columns] = sales_df[product_columns].fillna(0)

In [135]:
sales_df.duplicated().sum()

np.int64(0)

In [136]:
sales_long = sales_df.melt(
    id_vars=id_columns,
    value_vars=product_columns,
    var_name='product',
    value_name='quantity'
)

In [112]:
sales_long = sales_long[sales_long['quantity'] > 0]

In [113]:
sales_long.head(20)

              datetime day of week    total place    product  quantity
0  2019-07-11 15:35:00        Thur  23800.0   NaN  angbutter       1.0
1  2019-07-11 16:10:00        Thur  15800.0   NaN  angbutter       1.0
3  2019-07-13 13:19:00         Sat  14800.0   NaN  angbutter       1.0
4  2019-07-13 13:22:00         Sat  15600.0   NaN  angbutter       2.0
5  2019-07-13 14:54:00         Sat  15800.0   NaN  angbutter       1.0
6  2019-07-13 15:08:00         Sat  15800.0   NaN  angbutter       1.0
8  2019-07-13 15:23:00         Sat  19100.0   NaN  angbutter       2.0
9  2019-07-13 16:32:00         Sat  22300.0   NaN  angbutter       1.0
10 2019-07-14 11:08:00         Sun  15300.0   NaN  angbutter       1.0
11 2019-07-14 11:15:00         Sun  27600.0   NaN  angbutter       2.0
12 2019-07-14 11:44:00         Sun  26300.0   NaN  angbutter       1.0
13 2019-07-14 11:59:00         Sun  19800.0   NaN  angbutter       1.0
14 2019-07-14 12:59:00         Sun  18300.0   NaN  angbutter       1.0
15 2019-07-14 13:05:00         Sun  15600.0   NaN  angbutter       2.0
16 2019-07-14 14:06:00         Sun  23600.0   NaN  angbutter       2.0
17 2019-07-14 14:41:00         Sun  20100.0   NaN  angbutter       2.0
18 2019-07-14 14:51:00         Sun  25600.0   NaN  angbutter       2.0
19 2019-07-14 15:02:00         Sun  19800.0   NaN  angbutter       1.0
20 2019-07-15 11:45:00         Mon  15100.0   NaN  angbutter       2.0
21 2019-07-15 16:21:00         Mon  15800.0   NaN  angbutter       1.0

In [149]:
df = sales_long.merge(
    price_df,
    left_on='product',
    right_on='Name',
    how='left'
)

In [150]:
df[df['price'].isnull()]

,datetime,day of week,total,place,product,quantity,Name,price
7263,2019-07-11 15:35:00,Thur,23800.0,NaN,americano,1.0,NaN,NaN
7264,2019-07-11 16:10:00,Thur,15800.0,NaN,americano,0.0,NaN,NaN
7265,2019-07-12 11:49:00,Fri,58000.0,NaN,americano,0.0,NaN,NaN
7266,2019-07-13 13:19:00,Sat,14800.0,NaN,americano,0.0,NaN,NaN
7267,2019-07-13 13:22:00,Sat,15600.0,NaN,americano,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...
48415,2020-05-02 11:39:00,Sat,19800.0,후평 1동,vanila latte,0.0,NaN,NaN
48416,2020-05-02 12:15:00,Sat,14300.0,효자 2동,vanila latte,0.0,NaN,NaN
48417,2020-05-02 13:45:00,Sat,15000.0,소양동,vanila latte,0.0,NaN,NaN
48418,2020-05-02 14:45:00,Sat,24100.0,효자 1동,vanila latte,0.0,NaN,NaN
48419,2020-06-18 14:52:00,NaN,NaN,NaN,vanila latte,0.0,NaN,NaN

In [151]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 55683 entries, 0 to 55682
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   datetime     55683 non-null  datetime64[us]
 1   day of week  55660 non-null  str
 2   total        55660 non-null  float64
 3   place        49818 non-null  str
 4   product      55683 non-null  str
 5   quantity     55683 non-null  float64
 6   Name         41157 non-null  str
 7   price        41157 non-null  str
dtypes: datetime64[us](1), float64(2), str(5)
memory usage: 3.4 MB

                         datetime         total      quantity
count                       55683  5.566000e+04  55683.000000
mean   2019-12-11 16:31:45.997521  2.117252e+04      0.194673
min           2019-07-11 15:35:00  1.280000e+04      0.000000
25%           2019-09-22 13:01:00  1.580000e+04      0.000000
50%           2019-12-15 12:14:00  1.850000e+04      0.000000
75%           2020-02-26 16:13:00  2.300000e+04      0.000000
max           2020-06-18 14:52:00  1.293000e+06     16.000000
std                           NaN  2.699193e+04      0.556685

In [141]:
df.head()

,datetime,day of week,total,place,product,quantity,Name,price
0,2019-07-11 15:35:00,Thur,23800.0,NaN,angbutter,1.0,angbutter,4800
1,2019-07-11 16:10:00,Thur,15800.0,NaN,angbutter,1.0,angbutter,4800
2,2019-07-12 11:49:00,Fri,58000.0,NaN,angbutter,0.0,angbutter,4800
3,2019-07-13 13:19:00,Sat,14800.0,NaN,angbutter,1.0,angbutter,4800
4,2019-07-13 13:22:00,Sat,15600.0,NaN,angbutter,2.0,angbutter,4800

In [152]:
# ==========================================
# VALIDACIÓN DE PRODUCTOS SIN PRECIO
# ==========================================

missing_prices = df['price'].isnull().sum()

print("Productos sin precio:", missing_prices)

# visualizar productos problemáticos
df[df['price'].isnull()]

Productos sin precio: 14526

,datetime,day of week,total,place,product,quantity,Name,price
7263,2019-07-11 15:35:00,Thur,23800.0,NaN,americano,1.0,NaN,NaN
7264,2019-07-11 16:10:00,Thur,15800.0,NaN,americano,0.0,NaN,NaN
7265,2019-07-12 11:49:00,Fri,58000.0,NaN,americano,0.0,NaN,NaN
7266,2019-07-13 13:19:00,Sat,14800.0,NaN,americano,0.0,NaN,NaN
7267,2019-07-13 13:22:00,Sat,15600.0,NaN,americano,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...
48415,2020-05-02 11:39:00,Sat,19800.0,후평 1동,vanila latte,0.0,NaN,NaN
48416,2020-05-02 12:15:00,Sat,14300.0,효자 2동,vanila latte,0.0,NaN,NaN
48417,2020-05-02 13:45:00,Sat,15000.0,소양동,vanila latte,0.0,NaN,NaN
48418,2020-05-02 14:45:00,Sat,24100.0,효자 1동,vanila latte,0.0,NaN,NaN
48419,2020-06-18 14:52:00,NaN,NaN,NaN,vanila latte,0.0,NaN,NaN

NameError: name 'Name' is not defined